quant:
    a_qconfig:
        quantizer: LSQFakeQuantize
        observer: MSEObserver
        bit: 8
        symmetric: False
        ch_axis: -1
    w_qconfig:
        quantizer: AdaRoundFakeQuantize
        observer: MSEObserver
        bit: 4
        symmetric: False
        ch_axis: 0
    calibrate: 1024
    recon:
        cali_path: ""
        cali_n: 256
        cali_st: 25
        batch_size: 32
        scale_lr: 4.0e-5
        warm_up: 0.2
        weight: 0.01
        iters: 20000
        b_range: [20, 2]
        keep_gpu: True
        round_mode: learned_hard_sigmoid
        drop_prob: 0.5
process:
    seed: 0
DiT:
    image_size: 256
    model: "DiT-XL/2"
    num_classes: 1000
    ckpt_path: ""  
    num_sampling_steps: 100
    cfg_scale: 1.5
    cfg_scale_test: 4
    sample_dir: ""
    per_proc_batch_size: 16
    num_fid_samples: 10000
